### ISSUE TITLE
Error happened!: Command 'regtools junctions extract -i 5 -I 10000000 tests/test.bam -o test.bed' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ptnaimelmm** [ylab-hi/ScanExitron#1]
Hi there,

An error occurred when I use ScanExitron to analyze test data in the packages. Have you met this problem previously? Any suggestions? Thanks.
 
Error happened!: Command 'regtools junctions extract -i 5 -I 10000000 tests/test.bam -o test.bed' returned non-zero exit status 1. 
![test error](https://user-images.githubusercontent.com/30491288/115424508-c4acee80-a1cc-11eb-8211-ed07454350a6.png)
File "ScanExitron.py", line 136, in junction_caller
    cmd = 'regtools junctions annotate {0} {1} {2} -o {3}.janno'.format(bed, fasta, gtf, out_name)
UnboundLocalError: local variable 'bed' referenced before assignment

**Comment by dolittle007** [comment]
Please try to use RegTools v0.4.2 or a lower version.
It seems that RegTools v0.5 API has changed a lot, including the parameters.
Thank you.

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for your suggestion.
I tried to use regtools version 0.4.2 and even a lower one 0.1.0, but still
got the same error as attached. What do you think the problem is ? Would
you please share with me all the package version information? Do you have
any other suggestions? Thanks a lot.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by dolittle007** [comment]
The error message clearly showed that you were using RegTools 0.5.2.
"got the same error" means you were using the same version of RegTools, even you installed a different version.
You can type in the command line: **regtools** to check the output. Like the following information.

> Program:	regtools
> Version:	0.4.0
> Usage:		regtools <command> [options]
> Command:	junctions		Tools that operate on feature junctions.
> 					(eg. exon-exon junctions from RNA-seq.)
> 		cis-ase			Tools related to allele specific expression in cis.
> 		cis-splice-effects	Tools related to splicing effects of variants.
> 		variants		Tools that operate on variants.

You have to type "**which regtools**" to see which RegTools you were using. You may need to change the $PATH environment variable, as well.

Thank you for your suggestions, I will update the README to emphasize that only RegTools (v0.4) works.

**Comment by dolittle007** [comment]
I've made a small modification to ScanExitron, it can work with RegTools v0.5.0 now.
Thank you.

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for your help. I ran this program with regtools 0.5.0, but still got
the same error as attached. Sorry for the trouble.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by dolittle007** [comment]
I have updated the README. 
I've tested it. It works fine on RegTools v0.4.2.

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for the update. I installed regtools-0.4.2 and ran ScanExitron
successfully with test data.
However, I got another error attached from ScanExitron.py when I ran my own
dataset. Which align software do you use to generate the input bam file?
Besides, it seems ScanExitron only accepts gencode.v19 and v21 gtf and its
CDS.bed. When I used gencode v33, it got several errors. Hope you can give
me some suggestions. Thanks.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by dolittle007** [comment]
Hi, I've tested it using the latest Gencode v37 GTF and its corresponding CDS bed file.
It works fine. The output is the same as the one in the tests folder, except for the gene version (ENSG00000005379.17, ENSG00000005884.18).

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Sorry for the trouble. Could you show me all your conda package version
information? It seems something is wrong with bedtools. BTW, would you mind
running my bam file on your side if I send you one bam file? Thanks a lot.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by ptnaimelmm** [comment]
Hi Carlos,

I wish you had a nice weekend.
I exactly followed your updated information in README in github. I
successfully ran your test.bam in your package, but I failed at the last
part when I analyzed my own data. It said I got a valueError in
get_value_by_key m,n =k.split (delimiter). I tried to process my bam file
from both Hisat2 and STAR as that of your test.bam. Uniquely mapped reads
with MAPQ>50 were extracted from my BAM files with "samtools view -q 50 -b
chr17".  I searched for a solution on the Internet, but I failed. I am a
rookie in programming, would you please give me any suggestions? Attached
are the error message and part of my bam file. Could you analyze my data
using Scanexitron when you are free? It is quite important to run
ScanExitron successfully, as we highly suspect exitrons exist in our
samples. Thanks very much in advance.

Best regards,

MIngming
 SRR10316392q50chr17.rar
<https://drive.google.com/file/d/1u8R9On049w_sOdexYybal7gMq4pKL19G/view?usp=drive_web>



Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by dolittle007** [comment]
Thank you.
It is an issue introduced by gtf2bed.
I cannot access your attached files, but I analyzed SRR10316392 from NCBI SRA.
[SRR10316392.chr17.exitron.txt](https://github.com/ylab-hi/ScanExitron/files/6380376/chr17.exitron.txt)

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for your help. I exactly used bedops (v2.4.38) to generate CDS.bed
files. If there was something wrong with the CDS.bed file, it is supposed I
should also get an error for test.bam in the package, but I ran it
successfully. I am not sure whether I understand it correctly or not.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by fuhao1216** [comment]
> Hi there,
> 
> An error occurred when I use ScanExitron to analyze test data in the packages. Have you met this problem previously? Any suggestions? Thanks.
> 
> Error happened!: Command 'regtools junctions extract -i 5 -I 10000000 tests/test.bam -o test.bed' returned non-zero exit status 1.
> ![test error](https://user-images.githubusercontent.com/30491288/115424508-c4acee80-a1cc-11eb-8211-ed07454350a6.png)
> File "ScanExitron.py", line 136, in junction_caller
> cmd = 'regtools junctions annotate {0} {1} {2} -o {3}.janno'.format(bed, fasta, gtf, out_name)
> UnboundLocalError: local variable 'bed' referenced before assignment

same question ,have u solved it?

**Comment by dolittle007** [comment]
@fuhao1216,  It seems that you used RegTools v0.5.2, If you install RegTools 0.4.2 as the README indicated the problem will disappear.

**Comment by dolittle007** [comment]
@ptnaimelmm GTF2BED will add additional "zero_length_insertion" tag to BED file. ScanExitron can handle it correctly, after a small modification.

**Comment by ptnaimelmm** [comment]
Hi,

I installed regtools0.4.2 instead, then I can run it successfully.

Best regards,


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for your update. Have you ever tried to write a program to compare
exitron output files from two samples? Thanks.

Best regards,

Mingming


Mingming Liu, Ph.D.

Postdoctoral fellow, Dr. Jiou Wang's lab

Department of Biochemistry & Molecular Biology

Bloomberg School of Public Health

The Johns Hopkins University

**Comment by dolittle007** [comment]
@ptnaimelmm, Researchers can do a lot of downstream analysis using the identified exitrons based on their projects.
The output files are tab-delimited text files, you can achieve your goal using R or Python or any programing language.

**Comment by dolittle007** [comment]
The problems have been solved.
