### ISSUE TITLE
How to generate exitron-derived frameshift peptide sequences

### ISSUE THREAD

**Issue by ptnaimelmm** [ylab-hi/ScanExitron#10]
Hi Carlos,

Would you please share how you generate the protein sequences derived from frameshift caused by exitron events? You can not access exitron derived peptides from MS raw data if you do not have these variant peptide sequences in the protein database for MSGFplus searching in cptac.py application. Did I understand it correctly? Thanks.

**Comment by dolittle007** [comment]
You are correct.
You can try to use ScanNeo to generate predicted exitron-derived peptides.
The input is a VEP annotated VCF file.
```
ScanNeo.py fasta -i input.vcf -o output.fasta
```

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thank you so much for adding this new function here. It seems this program only generates protein sequences from exitron-contained isoforms using the original open reading frame. Do you think it will be better if we translate these variant RNAs in 3 frames, as I mentioned many predicted neopeptides come from other translation frame. Thanks.

**Comment by dolittle007** [comment]
You are right.
By definition, exitrons are within annotated coding exons. So exitron-derived peptides should be using the start codon of the transcript with the exitrons.
