### ISSUE TITLE
regtools junctions annotate error

### ISSUE THREAD

**Issue by macoreL** [ylab-hi/ScanExitron#11]
Hi, some errors happened when i used Scanexitron. The snapshot was shown: 
![1688395078558](https://github.com/ylab-hi/ScanExitron/assets/40660066/32454d8a-736b-4630-8eb0-385dc8c62127)
Scanexitron can run successfully using test data. I only change the reference genome for my data.
The command "cat Homo_sapiens.GRCh38.109.gtf | awk 'OFS="\t" {if ($3=="CDS") {print $1,$4-1,$5,$10,$20,$7}}' | tr -d '";' > Homo_sapiens.GRCh38.109.CDS.bed " was used to generate CDS file.
could you please tell me what is wrong and how to fix this?
Thank you

**Comment by nttg8100** [comment]
I had similar issue, then I found that the error may come from the fasta file, gtf file. It is quite early at the beginning of the chromosome so we may have so many NNNNNNN then it failed to extract I guess. I got this issue on the chromosome 10. As a result, I change to use the gtf gencode v37, hg38 from ucsc for fa. It solved the issue.
