### ISSUE TITLE
What's the difference between lower cases and the upper cases in splice_site in janno file?

### ISSUE THREAD

**Issue by ptnaimelmm** [ylab-hi/ScanExitron#3]
Hi, 
What's the difference between lower cases and the upper cases in splice_site column in janno file? 
Take GT-AG as an example, 
gt-ag
gt-aG
gt-Ag
gt-AG
gT-ag
gT-AG
Gt-ag
Gt-aG
Gt-AG
GT-ag
GT-aG
GT-Ag
GT-AG

Thanks

**Comment by dolittle007** [comment]
RegTools extract these splice sites from the human reference genome FASTA file directly.
Here shows the answers.
https://bioinformatics.stackexchange.com/questions/225/uppercase-vs-lowercase-letters-in-reference-genome
