### ISSUE TITLE
Problem working with unstranded data

### ISSUE THREAD

**Issue by markddesimone** [ylab-hi/ScanExitron#5]
Hi, I am trying to use ScanExitron but my data is unstranded. regtools therefore writes ? in the strand column and `junction_overlap_CDS_to_position_BED` prevents any junctions being detected. due to the test: 
```py
if stats == 'N' and strand != '?
```
e.g. the janno file contains:
|chrom|	start	|end|	name|	score|	strand|	splice_site|	acceptors_skipped|	exons_skipped|	donors_skipped|	anchor|	known_donor|known_acceptor|	known_junction|	gene_names|	gene_ids	|transcripts|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|chr1|	133276|	659397|	JUNC00000001|	1|	?|	CG-GT|	0|	0|	0|	N|	0|	0|	0|NA|	NA|	NA|

Is there any way to use or modify ScanExitron to work with unstranded data?

thank you

**Comment by dolittle007** [comment]
ScanExitron now supports the parameter for RNA-Seq strandness.
 0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR.
