### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MengyuanLyu** [ylab-hi/ScanExitron#6]
Hello, 
I am trying to use ScanExitron. However, it showed the error.

Junctions intersect with CDS
Junctions intersect with CDS finished!
Traceback (most recent call last):
  File "/root/miniconda3/envs/scanexitron/bin/ScanExitron-1.1-beta/ScanExitron.py", line 387, in <module>
    main()
  File "/root/miniconda3/envs/scanexitron/bin/ScanExitron-1.1-beta/ScanExitron.py", line 379, in main
    src_exitron_file, position_bed_file = junction_overlap_CDS_to_position_BED(janno_file, ref=args.ref)
  File "/root/miniconda3/envs/scanexitron/bin/ScanExitron-1.1-beta/ScanExitron.py", line 209, in junction_overlap_CDS_to_position_BED
    attr = get_value_by_key(l[16], delimiter=' ')
IndexError: list index out of range

I have tried to revise my index, but it did not work. 
Hope your guidance！ Thank you!

**Comment by dolittle007** [comment]
Thank you for your interest in using ScanExitron.
I have removed the get_value_by_key function in 1.3beta, please install the latest version.
I have changed the way of generating the CDS bed file, please change this file accordingly, as well.

**Comment by MengyuanLyu** [comment]
> Thank you for your interest in using ScanExitron.
> I have removed the get_value_by_key function in 1.3beta, please install the latest version.
> I have changed the way of generating the CDS bed file, please change this file accordingly, as well.

OK！Thank you!
