### ISSUE TITLE
Detailed workflow of cptac.py in the application folder

### ISSUE THREAD

**Issue by ptnaimelmm** [ylab-hi/ScanExitron#7]
Hi there,

Could you please provide a detailed workflow for cptac.py identifying exitron-derived polypeptides? Thanks in advance.

**Comment by ptnaimelmm** [comment]
Hi,
IDMerger could not be found when running cptac.py. Besides, I wonder where .exitron file was used in cptac.py. Thanks.

**Comment by dolittle007** [comment]
**IDMerger** is part of OpenMS(https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_IDMerger.html).
Another command such as **MSGFPlusAdapter** is also part of OpenMS.
If you have installed OpenMS successfully, you will see them.

**Comment by ptnaimelmm** [comment]
Thanks. Unfortunately, I failed to build OpenMS in my system.

**Comment by ptnaimelmm** [comment]
Hi, 
I successfully installed OpenMS in my system. However, I got an error as attached. What do you think the problem is and can you give me any suggestions? Thanks.
![cptac_error](https://user-images.githubusercontent.com/30491288/139516305-ac69eaa4-d52e-4e25-bb1c-e20c9d506732.png)

**Comment by dolittle007** [comment]
The error message clearly showed that the error happened at 'MSGFPlusAdapter'. the parameter file version did not match.
The database contains letter of 'U', which does not correspond to an amino acid.
You may need to read the error message carefully and locate the problem.

**Comment by ptnaimelmm** [comment]
Hi Carlos,

Thanks for your reply. Actually, I noticed it and removed Us in the
database sequence, but I still got the error message on java invocation as
follows.
***@***.***/Scanexitron_env) ***@***.***@compute0194
exitron_NeurolinC]$ ~/Scanexitron_env/bin/MSGFPlusAdapter -ini
~/privatemodules/ScanExitron/Applications/config/config.ini -in
Masspec/testTof/Tutorial_TOFCalibration_raw.mzML -out Testtof.idXML
-database hspro.fasta -executable
~/Scanexitron_env/share/msgf_plus-2017.07.21-1/MSGFPlus.jar -java_memory
20000 -threads 16
Warning: Parameters file version (2.4.0-HEAD-2018-10-26) does not match the
version of this tool (2.5.0-HEAD-HASH-NOTFOUND-HEAD-HASH-NOTFOUND).
Your current parameters are still valid, but there might be new valid
values or even new parameters. Upgrading the INI might be useful.
Running MSGFPlus search...
Executing: ***@***.***/Scanexitron_env/bin/java
FATAL ERROR: External invocation of /home-3/
***@***.***/Scanexitron_env/bin/java failed. Standard output and error
were:
Standard output: MS-GF+ Release (v2017.07.21) (21 July 2017)
Loading database files...
Creating the suffix array indexed file... Size: 45394295
AlphabetSize: 28
Suffix creation: 0.00% complete.
Suffix creation: 22.03% complete.
Suffix creation: 44.06% complete.
Suffix creation: 66.09% complete.
Suffix creation: 88.12% complete.
Sorting 0.00% complete.
Sorting 5.81% complete.
Sorting 11.62% complete.
Sorting 17.43% complete.
Sorting 23.24% complete.
Sorting 29.05% complete.
Sorting 34.86% complete.
Sorting 40.67% complete.
Sorting 46.48% complete.
Sorting 52.29% complete.
Sorting 58.10% complete.
Sorting 63.91% complete.
Sorting 69.73% complete.
Sorting 75.54% complete.
Sorting 81.35% complete.
Sorting 87.16% complete.
Sorting 92.97% complete.
Sorting 98.78% complete.
Loading database finished (elapsed time: 42.02 sec)
Reading spectra...

Standard error: Exception in thread "main"
java.lang.ExceptionInInitializerError
        at uk.ac.ebi.jmzml.xml.Constants.<clinit>(Constants.java:56)
        at
uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:82)
        at
uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
        at
uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
        at
uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
        at
uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
        at edu.ucsd.msjava.mzml.MzMLAdapter.<init>(MzMLAdapter.java:27)
        at
edu.ucsd.msjava.msutil.SpectraAccessor.getSpecMap(SpectraAccessor.java:38)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:217)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
        at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException:
com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:186)
        at uk.ac.ebi.jmzml.MzMLElement.loadProperties(MzMLElement.java:609)
        at uk.ac.ebi.jmzml.MzMLElement.<init>(MzMLElement.java:564)
        at uk.ac.ebi.jmzml.MzMLElement.<clinit>(MzMLElement.java:83)
        ... 11 more
Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException:
com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:455)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
        at javax.xml.bind.JAXB$Cache.<init>(JAXB.java:127)
        at javax.xml.bind.JAXB.getContext(JAXB.java:154)
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:183)
        ... 14 more
Caused by: java.lang.ClassNotFoundException:
com.sun.xml.internal.bind.v2.ContextFactory
        at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at
javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
        ... 20 more

Exit code: 1

**Comment by dolittle007** [comment]
There is something wrong with the JAVA you installed.
(https://mkyong.com/java/java-lang-classnotfoundexception-com-sun-xml-bind-v2-contextfactory/)
You may need to install an older version of JAVA. (Maybe Java 8)

**Comment by ptnaimelmm** [comment]
I tried Java8 previously, but got quite similar error notes. Maybe I can try other versions of JAVA. Thanks.

**Comment by dolittle007** [comment]
Dealing with software dependency is a daunting task.
You can use anaconda (https://www.anaconda.com/) to install all OpenMS and java.
To make it work, you may need to create a new Conda environment, then install all the necessary packages, including msgf_plus, openms.

Hope it helps.
