### ISSUE TITLE
line 215: length-1 

### ISSUE THREAD

**Issue by zyh4482** [ylab-hi/ScanExitron#8]
Hi. 
The width of a range is usually calculated by `end - start` in 0-start half-open system. 
May I ask why the exitron length in `scanExitron.py line215` is called by `length-1 ` ?

**Comment by dolittle007** [comment]
ScanExitron makes use of Regtools called splicing junctions as input.
Regtools used 1bp adjacent to the junction as the start and end. 
So Scanexitron has to fix this problem. 
You may load the BAM file into IGV to check the junctions called by Regtools in the corresponding janno file.

**Comment by zyh4482** [comment]
Thank you!
